<?php

 include("header.php");

 echo "
 <h2>Reconstructed Proto-Bantu Roots (PBR)</h2>

    <p><a href=\"#moye\"><b><i>*moye</i></b></a></p>
    <p><a href=\"#simb\"><b><i>*simb</i></b></a></p>
    <p><a href=\"#sung\"><b><i>*sung</i></b></a></p>
    <p><a href=\"#yadi\"><b><i>*yadi</i></b></a></p>
    <hr>
    
    <p id=\"moye\" style=\"text-align:justify\"><b><i>*moye</i></b><br />
	*moye is a root that has a very limited distribution among Botatwe and some Sabi speaking peoples and by its varied meanings probably is another term for a girl from puberty and prior to marriage.  For example in Soli it means both initiate, moye and bride, moye; in Tonga both a girl prior to initiation and after initiation is mooye; in Lenje mooye means unitiated girl and virgin; and in Lamba moye means girl, young girl, and pubescent girl (and they also use the term kamwale from *yadi).
	While the distribution of *moye  is quite limited to Bantu speaking peoples of Zambia, its other meaning is relevent to the study of life stages.  *moye also means cacoon, and is a metaphor for how people thought of a young woman's transformation during female initiation.</p>";

    echo "<p id=\"simb\" style=\"text-align:justify\"><b><i>*simb</i></b><br />
  
	*simb may mean the opposite, a lack of reproduction possibilities-temporary or permanent. In proto-Bantu there are at least three meanings for this root, the one that is most relevant for understanding lifestages is from the proto-Bantu root  (CS 354) *-cimb-, \"to prevent, to cease.\"  Since *-simb is used to indicate a girl, a girl ready for initiation, a girl prior to initiation, bachelors, unmarried person, a virgin or a maiden-all roles in which reproduction  should or could not occur. Most Bantu-speaking peoples believed that if a young woman got pregnant prior to initiation that it was very dangerous.   *simb also is used for the roles of widows and abandoned wives, people who have ceased reproductive activity-at least temporarily. Again this appears to apply to both male and female, who either aren\'t ready or have temporarily ceased sexual activities.   The distribution of *simb meaning temporarily no sexual or reproductive activity is limited to peoples speaking one of the four branches of Savanna Bantu in Central Africa , whereas the use of *simb to indicated ceased reproductive activity is found only in Eastern Bantu.  The last time the ancestors of these different Bantu speaking peoples lived in close proximity was about 1000BCE, so probably this term is at least 3000 years old.</p>";
	
	echo "<p id=\"sung\" style=\"text-align:justify\"><b><i>*sung</i></b><br />
	
	*sung and its meanings probably dates earlier than 3000 years ago since it is found in many  Savanna Bantu language branches but also in two groups that separated from Savanna Bantu around 2000BCE. *sung is derived by the proto-Bantu root *-cungu (CS. 421, 422) which probably originally meant \"to transform or to change\".  *sung is used often to indicate a brief period in a young woman\'s life usually  girl between puberty and female initiation.  Among the people speaking Eastern, Sabi, and Central  Savanna Bantu languages *sung is the term used to refer to  female puberty, adolescent girl, and nubile girl, as well as  ceremony after first menses, women in charge of female initiation, celebration after the second menses, female initiation and dances at female initiation.  For some matrilineal peoples *sung became a general term for woman, Bisa-cisungu anakazi; in Fipa-girlhood, unsung or female fiancee and in Mambwe-male fiance, sicisungu (si is often a male prefix. In Marungu, a Sabi language from Central Africa a nubile girl is sungwakazi and a young man is sungwalume.<br />
	&emsp;&emsp;The root *sung can also reveal the difference in worldview from societies that are matrilineal and practice female initiation from those that have become patrilineal and no longer celebrate puberty ceremonies.  For example among the Nyakusa, a bride  is unsungu and a marriage ceremony is ubusungu. In Nilamba a wife is musungu. The transformation of this word and concept from a girl at puberty to a wife indicates the significance placed on the marriage institution-since there are no longer female initiation rites. Also among some East Bantu speaking peoples of Southern Tanzania, age grades and male circumcision have been introduced to the region as the new uses of *sung indicate.  In Lungu, boy\'s age grade coming out is called itshisungu (note the si or shi male indicator); in Nyakusa the word sungwalume  (note the use of the male suffix) means male circumcision lodge and in Tsonga  terms for circumcision lodge and seclusion.  Among the Tonga of Southern Zambia, an ethno-linguistic group that still used matrilineal social organization use *sung to indicate the final marriage ceremony, insyungu.<br />
	&emsp;&emsp;The verbs made from the *sung root also help to shed light on its varied meanings. *sung in Bemba means to care for kusunga; in Sanga it means to raise an infant, sungula; and  in Mbosi, a Bantu language from the Central African republic and not part of the Savanna Bantu languages it means to help, to aid. In Mambwe -sunga means to retain for future use; in Kutu it is the term used to indicate the separation of chaff from the grain; in Yao to sieve filter beer is lisungulo, and in Tonga, sungulwa means to be release like a girl from her family-all these means indicate a change or a transition.  Tabwa uses kusungu to indicate the attainment of puberty. Thus *sung is a term that is gendered female for the most part and encompasses both the meaning of transition as in female initiation and the nurturing qualities ascribed to a mother.<br />
	&emsp;&emsp;To understand how ancient the word and concept behind *sung is involves looking at its distribution among Bantu speaking peoples. The Mbosi of the Central African Republic and the Lomongo of northeastern DRC both use this root.  Among the patrilineal Lomongo it means both fertility and the payment of brideprice. Since the ancestors of the modern Mbosi and Lomongo speaking peoples would have separated from the Savanna Bantu as early as four thousand years ago, *sung as an indicator of female puberty and transformation may date to 2000BCE.</p>";
	
	echo "<p id=\"yadi\" style=\"text-align:justify\"><b><i>*yadi</i></b><br />
	 The proto-Bantu root *-yadi has uncovered a crucial life stage for women from their first period to their first successful pregnancy.  This word is so widespread throughout Bantu -speaking Africa, that it must have been part of their worldview over five thousand years ago.  Comparative ethnographic data shows that at least in the last hundred years this life stage was celebrated by two female initiation ceremonies –one after the first or second menses and the final one either at four or five months of the first pregnancy or at the first birth.  Especially in matrilineal societies a derivation of this root is often used to designate a young woman in this lifestage.  Words for menses and female puberty are also based on this root.   Among some  Bantu speakers, the term for male initiates is also constructed from this root.  This probably indicates that male initiation might be a more recent addition to the social and spiritual life of these peoples.  The yadi lifestage includes marriage, but marriage does not transform the young woman into the next stage.   Also some communities use words based on the *-yadi root  for girl, virgin, woman, initiate, new wife, daughter, adolescent girl and maiden.  What this indicates is that while in English there are all these different terms that describe a female during this long period Bantu conceptualized a particular life stage from puberty to first pregnancy.</p>";

include("footer.php");

?>